---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-log-4yxy-io-v1-serverlog
  failurePolicy: Fail
  name: mserverlog.kb.io
  rules:
  - apiGroups:
    - log.4yxy.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serverlogs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-log-4yxy-io-v1-serverlog
  failurePolicy: Fail
  name: vserverlog.kb.io
  rules:
  - apiGroups:
    - log.4yxy.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serverlogs
  sideEffects: None
