---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - log.4yxy.io
  resources:
  - serverlogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - log.4yxy.io
  resources:
  - serverlogs/finalizers
  verbs:
  - update
- apiGroups:
  - log.4yxy.io
  resources:
  - serverlogs/status
  verbs:
  - get
  - patch
  - update
