# permissions for end users to edit serverlogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serverlog-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: log-collector
    app.kubernetes.io/part-of: log-collector
    app.kubernetes.io/managed-by: kustomize
  name: serverlog-editor-role
rules:
- apiGroups:
  - xy.io.xy.io
  resources:
  - serverlogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xy.io.xy.io
  resources:
  - serverlogs/status
  verbs:
  - get
